/* squash.c - single-file build of the squash compiler */
/* Include all implementation files in dependency order */
#include "log.c"
#include "ast.c"
#include "symtable.c"
#include "lexer.c"
#include "diag.c"
#include "assembler.c"
#include "linker.c"
#include "winlinker.c"
#include "parser_new4.c"
#include "codegen.c"
#include "arm64_asm.c"
#include "codegen_arm64.c"
#include "pe_builder.c"
#include "elf_builder.c"
#include "macho_builder.c"
#include "objfile.c"
#include "implib.c"
#include "compiler.c"
