/* GENERATED by build_example.sh from examples/audio/04-multiple-streams/multiple-streams.c -- do not edit directly. */
/* SDL_MAIN_HANDLED: tells <SDL3/SDL_main.h> (pulled in by every example via
 * its own "#define SDL_MAIN_USE_CALLBACKS 1" + "#include <SDL3/SDL_main.h>")
 * to skip including SDL3/SDL_main_impl.h's generated main()/SDL_main()
 * wrapper, which calls SDL_EnterAppMainCallbacks() -- part of SDL3's real
 * src/main/ launcher, not included in this build's reduced sdl_core.inc
 * subset. Without this, that wrapper still gets compiled in as dead code
 * (example_shim.inc's own main() below is the only one actually called,
 * see its "#undef main" comment) but squash's macOS/ELF output binds
 * imports eagerly, so the mere presence of an unresolved reference to
 * SDL_EnterAppMainCallbacks crashes at process load, before main() ever
 * runs, even though nothing would have called it. */
#define SDL_MAIN_HANDLED
#include "examples/audio/04-multiple-streams/multiple-streams.c"
#include "example_shim.inc"
