#!/bin/bash
# Generates and builds one SDL3 example, linked against the pre-compiled
# SDL3_Build/sdl_common.sqo cache instead of recompiling all of SDL3 from
# source every time -- see objfile.h and sdl_common_obj.c for how squash's
# object-file support works. This turns each example build from a ~80s full
# unity recompile into a ~2s compile-and-link of just the example's own
# small source, since sdl_core.inc (the shared SDL3 subsystem body) never
# changes between examples.
#
# Usage: build_example.sh <path/to/example.c, relative to SDL3/SDL>
#   e.g. build_example.sh examples/renderer/01-clear/clear.c
#
# Run from the squash compiler's own root directory (same convention as
# every other squash invocation in this project -- see Makefile.SDL3's own
# header comment for why: squash's bundled libc shim resolves via a
# hardcoded CWD-relative "include/<name>.h" lookup, unrelated to -I).
#
# IMPORTANT: sdl_common.sqo must be rebuilt (`make -f Makefile.SDL3
# SDL3_Build/sdl_common.sqo`) whenever sdl_core.inc OR the squash compiler
# itself changes -- this script does not check staleness, the Makefile's
# dependency rule does.
#
# Generates SDL3_Build/examples_gen/<name>.c: a small driver source that
# #includes the example's own real, UNMODIFIED source file and
# example_shim.inc's SDL_main callback-loop driver (see its own header
# comment) -- NOT sdl_core.inc, which is already baked into sdl_common.sqo.
set -e

EX="$1"
# Optional: platform/arch flags and squash binary name, so the same script
# serves both Makefile.SDL3 (Windows, the default -- unchanged call sites)
# and Makefile.SDL3.linux (Linux, passes explicit args below). PLATFORM_FLAG
# is "-windows" or "-linux"; ARCH_FLAG is "-64" or "-arm64"; SQUASH_BIN lets
# Linux point at the real "./squash" binary instead of the Windows-only
# "./squash.exe" name that was previously hardcoded here (and simply didn't
# exist on a Linux checkout, meaning every Linux "make examples"/"example"
# call silently failed with "No such file or directory").
PLATFORM_FLAG="${2:--windows}"
ARCH_FLAG="${3:--64}"
SQUASH_BIN="${4:-./squash.exe}"
if [ -z "$EX" ]; then
    echo "usage: $0 <path/to/example.c relative to SDL3/SDL> [-windows|-linux] [-64|-arm64] [squash-binary]" >&2
    exit 1
fi

NAME=$(basename "$EX" .c)
GEN_DIR="SDL3_Build/examples_gen"
GEN="$GEN_DIR/$NAME.c"
# Arch-qualify the output/.sqo names on non-default (arm64) builds so an
# x64 and an arm64 build of the same example (or the shared sdl_common.sqo)
# never collide/overwrite each other -- required now that a ".sqo" carries
# an explicit arch tag (see objfile.h) and a mismatched one is a hard error.
SUFFIX=""
SQO="SDL3_Build/sdl_common.sqo"
if [ "$ARCH_FLAG" = "-arm64" ]; then
    SUFFIX="_arm64"
    SQO="SDL3_Build/sdl_common_arm64.sqo"
fi
EXT=".exe"
if [ "$PLATFORM_FLAG" = "-linux" ]; then
    EXT=""
fi
OUT="$GEN_DIR/$NAME$SUFFIX$EXT"

mkdir -p "$GEN_DIR"

cat > "$GEN" <<EOF
/* GENERATED by build_example.sh from $EX -- do not edit directly. */
#include "$EX"
#include "example_shim.inc"
EOF

"$SQUASH_BIN" "$PLATFORM_FLAG" "$ARCH_FLAG" \
    -ISDL3/SDL/include -ISDL3/SDL/src -ISDL3_Build \
    -ISDL3/SDL/include/build_config -ISDL3/SDL \
    "$GEN" "$SQO" -o "$OUT"
