/* Real PNG decode test through the newly-wired stb_image.h (see
 * sdl_core.inc's "video/SDL_stb.c" include) -- loads a real, valid PNG
 * file from disk via SDL_LoadPNG and checks basic decode correctness.
 * squash_test_image.png was generated by a separate, already-verified-
 * working standalone miniz encoder (see squash_build/scratch/write_png_file.c)
 * -- this test isolates the stb_image DECODE path (used by real texture-
 * loading examples) from the SDL_SavePNG encode path, which currently still
 * crashes only when built as part of the full combined sdl_core.inc
 * translation unit (see project notes) despite miniz.h working correctly
 * in isolation. */
#include "sdl_core.inc"

int main(void)
{
    dbgmark("main() entered");
    if (!SDL_Init(0)) {
        SDL_Log("SDL_Init failed: %s", SDL_GetError());
        return 1;
    }
    dbgmark("after SDL_Init");

    const char *path = "squash_test_image.png";
    dbgmark("before SDL_LoadPNG");
    SDL_Surface *loaded = SDL_LoadPNG(path);
    dbgmark("after SDL_LoadPNG");
    if (!loaded) {
        SDL_Log("SDL_LoadPNG failed: %s", SDL_GetError());
        return 1;
    }
    SDL_Log("SDL_LoadPNG OK: %dx%d format=%d", loaded->w, loaded->h, loaded->format);

    if (loaded->w != 17 || loaded->h != 13) {
        SDL_Log("MISMATCH: expected 17x13, got %dx%d", loaded->w, loaded->h);
        return 1;
    }

    SDL_DestroySurface(loaded);
    SDL_Log("PNG load test PASSED: 17x13 decoded correctly");
    dbgmark("before SDL_Quit");
    SDL_Quit();
    return 0;
}
