/* Part 3/3 of the split SDL3 build (see sdl_shared_defs.inc's own comment):
 * the video/render subsystem, including the custom PRIVATE_* Win32 windowing
 * backend, software renderer, blend helpers, and stb_image.h/miniz.h PNG/JPEG
 * decode. Also hosts squash_init_private_bootstrap() (wires up BOTH this
 * part's own PRIVATE_bootstrap AND sdl_part_audio.sqo's PRIVATEAUDIO_bootstrap
 * -- a real cross-object global-variable write, only correctly resolved
 * since objfile.c's objfile_merge() gained cross-object global-variable
 * support alongside this split) and squash_init_private_bootstrap's own
 * dbgmark() tracing helper. Compiled once via "squash -c" to
 * sdl_part_video.sqo. GENERATED by splitting sdl_core.inc verbatim -- see
 * sdl_part_core.c's own comment. */
#include "sdl_shared_defs.inc"

/* AudioBootStrap / the "extern AudioBootStrap PRIVATEAUDIO_bootstrap;"
 * declaration this file needs both come straight from SDL3's own header --
 * PRIVATEAUDIO_bootstrap itself is a real (non-static) global DEFINED in
 * sdl_part_audio.c/sdl_part_audio.sqo. squash_init_private_bootstrap()
 * below writes its fields directly, same as it always has, now resolved
 * across the object-file boundary at link time instead of within one TU. */
#include "audio/SDL_sysaudio.h"

/* PRIVATEAUDIO_Init is defined (as a plain function -- squash's flat symbol
 * table has no real per-TU "static" scoping, so this resolves as an
 * ordinary cross-object call, same mechanism as any other exported
 * function) in sdl_part_audio.c. A bodyless "extern" declaration here is
 * what makes squash defer this to the cross-object RELOC_STATIC_REL32 path
 * (see parser_new4.c's ParseFunction) instead of trying to resolve it
 * within this TU and failing. */
extern bool PRIVATEAUDIO_Init(SDL_AudioDriverImpl *impl);

/* WIN_SetError/WIN_SetErrorFromHRESULT's real definitions (squash's own
 * project-specific replacement for SDL3's excluded core/windows/SDL_windows.c
 * -- see sdl_part_core.c) live in sdl_part_core.c. Same cross-object
 * "extern" forward-declaration story as PRIVATEAUDIO_Init just above. */
extern bool WIN_SetError(const char *prefix);

/* HWND/HDC/GDI calls etc. come from squash's own include/windows.h shim --
 * see sdl_part_audio.c's identical comment for why this part needs its own
 * explicit include now that it's a separate TU from whichever "core" file
 * used to pull this in first in the original single-TU unity build. */
#include <windows.h>

/* SDL_VideoDevice (used by this part's own PRIVATE_VideoInit() etc., BEFORE
 * video/SDL_video.c below is what would otherwise define it) used to arrive
 * transitively via events/SDL_events.c's own #include chain -- events is
 * now compiled into sdl_part_core.sqo instead, a separate TU, so this part
 * needs the same header directly. */
#include "video/SDL_sysvideo.h"

/* ============================================================================
 * Custom SDL_VIDEO_DRIVER_PRIVATE backend: a real (not dummy) minimal Win32
 * windowing implementation, hand-written directly in this TU rather than
 * including SDL3's own video/windows/*.c (which pulls in IME, raw input,
 * drag-and-drop OLE, tablet/pen, GameInput.cpp (C++), and high-DPI-awareness
 * context APIs well beyond this build's scope). Modeled on the same
 * RegisterClassExA/CreateWindowExA/PeekMessageA pattern already proven
 * working in tests/test_gl45_windows.c, plus a GDI DIB-section framebuffer
 * (CreateDIBSection/BitBlt) matching the technique in SDL3's own real
 * video/windows/SDL_windowsframebuffer.c — this is what lets the portable
 * SDL_VIDEO_RENDER_SW software renderer (render/software/SDL_render_sw.c,
 * included below) actually put pixels on screen via SDL_GetWindowSurface()/
 * SDL_UpdateWindowSurface(). No keyboard/mouse/OpenGL/Vulkan hookup yet —
 * just enough to create/show/resize/close a window and blit a software
 * framebuffer to it. See [[project-squash-sdl3-build]] memory notes.
 * ============================================================================ */
static void dbgmark(const char *s);
static void dbgmark_ptr(const char *label, unsigned long long v);

struct SDL_WindowData {
    HWND   hwnd;
    HDC    hdc;  /* window DC, valid for the window's lifetime (CS_OWNDC) */
    HDC    mdc;  /* memory DC selected with the framebuffer DIB section */
    HANDLE hbm;  /* the DIB section bitmap backing the framebuffer */
};

static const char *SQUASH_WNDCLASS_NAME = "SquashSDLWindowClass";

static LRESULT CALLBACK squash_wnd_proc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    SDL_Window *window = (SDL_Window *)(size_t)GetWindowLongPtrA(hwnd, GWLP_USERDATA);
    switch (msg) {
        case WM_CLOSE:
            if (window) {
                SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_CLOSE_REQUESTED, 0, 0);
            }
            return 0;
        case WM_DESTROY:
            return 0;
        case WM_SIZE: {
            if (window) {
                int w = (int)(lp & 0xFFFF);
                int h = (int)((lp >> 16) & 0xFFFF);
                if (w > 0 && h > 0) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, w, h);
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESIZED, w, h);
                }
            }
            return 0;
        }
        default:
            break;
    }
    return DefWindowProcA(hwnd, msg, wp, lp);
}

static bool PRIVATE_VideoInit(SDL_VideoDevice *_this)
{
    SDL_DisplayMode mode;
    SDL_zero(mode);
    mode.format = SDL_PIXELFORMAT_XRGB8888;
    mode.w = GetSystemMetrics(SM_CXSCREEN);
    mode.h = GetSystemMetrics(SM_CYSCREEN);
    if (mode.w <= 0) mode.w = 1920;
    if (mode.h <= 0) mode.h = 1080;
    if (SDL_AddBasicVideoDisplay(&mode) == 0) {
        return false;
    }

    WNDCLASSEXA wc;
    SDL_zero(wc);
    wc.cbSize = sizeof(wc);
    wc.style = CS_HREDRAW | CS_VREDRAW | CS_OWNDC | CS_DBLCLKS;
    wc.lpfnWndProc = squash_wnd_proc;
    wc.hInstance = GetModuleHandleA(NULL);
    wc.hCursor = LoadCursorA(NULL, IDC_ARROW);
    wc.lpszClassName = SQUASH_WNDCLASS_NAME;
    RegisterClassExA(&wc); /* failure is harmless here (e.g. re-Init) */

    return true;
}

static void PRIVATE_VideoQuit(SDL_VideoDevice *_this)
{
    (void)_this;
}

static bool PRIVATE_CreateSDLWindow(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID create_props)
{
    (void)_this; (void)create_props;
    DWORD style = WS_OVERLAPPEDWINDOW;
    RECT r;
    r.left = 0; r.top = 0; r.right = window->w; r.bottom = window->h;
    AdjustWindowRect(&r, style, FALSE);

    SDL_WindowData *data = (SDL_WindowData *)SDL_calloc(1, sizeof(*data));
    if (!data) {
        return false;
    }

    HWND hwnd = CreateWindowExA(0, SQUASH_WNDCLASS_NAME, window->title ? window->title : "",
                                 style, CW_USEDEFAULT, CW_USEDEFAULT,
                                 r.right - r.left, r.bottom - r.top,
                                 NULL, NULL, GetModuleHandleA(NULL), NULL);
    if (!hwnd) {
        SDL_free(data);
        return WIN_SetError("CreateWindowExA failed");
    }

    data->hwnd = hwnd;
    data->hdc = GetDC(hwnd);
    SetWindowLongPtrA(hwnd, GWLP_USERDATA, (LONG_PTR)(size_t)window);
    window->internal = data;
    return true;
}

static void PRIVATE_SetWindowTitle(SDL_VideoDevice *_this, SDL_Window *window)
{
    (void)_this;
    SetWindowTextA(window->internal->hwnd, window->title ? window->title : "");
}

static void PRIVATE_ShowWindow(SDL_VideoDevice *_this, SDL_Window *window)
{
    (void)_this;
    ShowWindow(window->internal->hwnd, SW_SHOW);
    UpdateWindow(window->internal->hwnd);
}

static void PRIVATE_HideWindow(SDL_VideoDevice *_this, SDL_Window *window)
{
    (void)_this;
    ShowWindow(window->internal->hwnd, SW_HIDE);
}

static void PRIVATE_DestroyWindow(SDL_VideoDevice *_this, SDL_Window *window)
{
    (void)_this;
    SDL_WindowData *data = window->internal;
    if (!data) {
        return;
    }
    if (data->mdc) DeleteDC(data->mdc);
    if (data->hbm) DeleteObject(data->hbm);
    if (data->hdc) ReleaseDC(data->hwnd, data->hdc);
    if (data->hwnd) DestroyWindow(data->hwnd);
    SDL_free(data);
    window->internal = NULL;
}

static void PRIVATE_GetWindowSizeInPixels(SDL_VideoDevice *_this, SDL_Window *window, int *w, int *h)
{
    (void)_this;
    RECT r;
    GetClientRect(window->internal->hwnd, &r);
    *w = r.right - r.left;
    *h = r.bottom - r.top;
}

static void PRIVATE_PumpEvents(SDL_VideoDevice *_this)
{
    (void)_this;
    MSG msg;
    while (PeekMessageA(&msg, NULL, 0, 0, PM_REMOVE)) {
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }
}

static bool PRIVATE_CreateWindowFramebuffer(SDL_VideoDevice *_this, SDL_Window *window, SDL_PixelFormat *format, void **pixels, int *pitch)
{
    (void)_this;
    SDL_WindowData *data = window->internal;
    int w, h;
    PRIVATE_GetWindowSizeInPixels(_this, window, &w, &h);
    if (w <= 0) w = 1;
    if (h <= 0) h = 1;

    if (data->mdc) { DeleteDC(data->mdc); data->mdc = NULL; }
    if (data->hbm) { DeleteObject(data->hbm); data->hbm = NULL; }

    BITMAPINFO bi;
    SDL_zero(bi);
    bi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    bi.bmiHeader.biWidth = w;
    bi.bmiHeader.biHeight = -h; /* negative = top-down DIB, matches SDL's own row order */
    bi.bmiHeader.biPlanes = 1;
    bi.bmiHeader.biBitCount = 32;
    bi.bmiHeader.biCompression = BI_RGB;

    *format = SDL_PIXELFORMAT_XRGB8888;
    *pitch = w * 4;

    data->mdc = CreateCompatibleDC(data->hdc);
    data->hbm = CreateDIBSection(data->hdc, &bi, DIB_RGB_COLORS, pixels, NULL, 0);
    if (!data->hbm) {
        return WIN_SetError("CreateDIBSection failed");
    }
    SelectObject(data->mdc, data->hbm);
    return true;
}

static bool PRIVATE_UpdateWindowFramebuffer(SDL_VideoDevice *_this, SDL_Window *window, const SDL_Rect *rects, int numrects)
{
    (void)_this;
    SDL_WindowData *data = window->internal;
    int i;
    for (i = 0; i < numrects; i++) {
        BitBlt(data->hdc, rects[i].x, rects[i].y, rects[i].w, rects[i].h,
               data->mdc, rects[i].x, rects[i].y, SRCCOPY);
    }
    return true;
}

static void PRIVATE_DestroyWindowFramebuffer(SDL_VideoDevice *_this, SDL_Window *window)
{
    (void)_this;
    SDL_WindowData *data = window->internal;
    if (!data) {
        return;
    }
    if (data->mdc) { DeleteDC(data->mdc); data->mdc = NULL; }
    if (data->hbm) { DeleteObject(data->hbm); data->hbm = NULL; }
}

static void PRIVATE_DeleteDevice(SDL_VideoDevice *device)
{
    SDL_free(device);
}

static SDL_VideoDevice *PRIVATE_CreateDevice(void)
{
    SDL_VideoDevice *device = (SDL_VideoDevice *)SDL_calloc(1, sizeof(*device));
    if (!device) {
        return NULL;
    }

    device->VideoInit = PRIVATE_VideoInit;
    device->VideoQuit = PRIVATE_VideoQuit;
    device->PumpEvents = PRIVATE_PumpEvents;
    device->CreateSDLWindow = PRIVATE_CreateSDLWindow;
    device->SetWindowTitle = PRIVATE_SetWindowTitle;
    device->ShowWindow = PRIVATE_ShowWindow;
    device->HideWindow = PRIVATE_HideWindow;
    device->DestroyWindow = PRIVATE_DestroyWindow;
    device->GetWindowSizeInPixels = PRIVATE_GetWindowSizeInPixels;
    device->CreateWindowFramebuffer = PRIVATE_CreateWindowFramebuffer;
    device->UpdateWindowFramebuffer = PRIVATE_UpdateWindowFramebuffer;
    device->DestroyWindowFramebuffer = PRIVATE_DestroyWindowFramebuffer;
    device->free = PRIVATE_DeleteDevice;
    return device;
}

/* NOT brace-initialized here (see squash_init_private_bootstrap(), called
 * first thing in main() below) — a global struct-with-function-pointer-field
 * brace initializer at this exact spot was observed (via a raw byte dump) to
 * read back as unrelated garbage after Pass 0.5's rewrite, still under
 * investigation as a genuine squash bug; assigning the fields as ordinary
 * runtime statements sidesteps it entirely and is just as correct. */
VideoBootStrap PRIVATE_bootstrap;

/* Not static: called from example_shim.inc / sdl_unity.c, which are
 * compiled as a SEPARATE translation unit from this file when linked
 * against squash_build/sdl_common.sqo (the cached-object build path) — a
 * static function has no visibility across that object-file boundary. */
void squash_init_private_bootstrap(void)
{
    PRIVATE_bootstrap.name = "private";
    PRIVATE_bootstrap.desc = "squash custom minimal Windows video driver";
    PRIVATE_bootstrap.create = PRIVATE_CreateDevice;
    PRIVATE_bootstrap.ShowMessageBox = NULL;
    PRIVATE_bootstrap.is_preferred = false;

    PRIVATEAUDIO_bootstrap.name = "private";
    PRIVATEAUDIO_bootstrap.desc = "squash custom minimal Windows audio driver";
    PRIVATEAUDIO_bootstrap.init = PRIVATEAUDIO_Init;
    PRIVATEAUDIO_bootstrap.demand_only = false;
    PRIVATEAUDIO_bootstrap.is_preferred = false;
}

/* SDL_build_config_minimal.h (forced by SDL_build_config_private.h) turns on
 * SDL_VIDEO_DRIVER_DUMMY unconditionally, which adds "&DUMMY_bootstrap," to
 * SDL_video.c's own bootstrap[] array (src/video/SDL_video.c, ~line 146) —
 * but this build never includes video/dummy/SDL_nullvideo.c (the file that
 * actually DEFINES DUMMY_bootstrap), so that array element referenced a
 * global with no body anywhere in the translation unit. Undefining the
 * macro here (same per-file config-override pattern as SDL_FSOPS_WINDOWS
 * elsewhere in this file) removes that #ifdef'd entry entirely, leaving
 * bootstrap[] as the intended {&PRIVATE_bootstrap, NULL}. */
#undef SDL_VIDEO_DRIVER_DUMMY
#include "video/SDL_pixels.c"
#include "video/SDL_rect.c"
#include "video/SDL_fillrect.c"
#include "video/SDL_surface.c"
#include "video/SDL_video.c"

/* TEMPORARY diagnostic for the video-split SDL_format_details hash-NULL
 * crash (see project memory) — calls the REAL SDL_CreateHashTable/
 * SDL_HashID/SDL_KeyMatchID/SDL_DestroyHashValue (all real, unmodified
 * SDL3 functions, just called directly from our own harness file instead
 * of via SDL_GetPixelFormatDetails' lazy-init path) with the exact same
 * argument shape SDL_pixels.c itself uses, immediately reading back
 * table->hash via a local struct shadowing the real (opaque-to-callers)
 * SDL_HashTable layout copied from SDL_hashtable.c line 40 for inspection
 * purposes only. Prints whether the returned table's own hash callback
 * pointer is NULL right after creation, and whether calling through it
 * directly (bypassing SDL_FindInHashTable/calc_hash entirely) crashes. */
struct squash_repro_hashtable_shadow {
    SDL_RWLock *lock;
    void *table;
    Uint32 (SDLCALL *hash)(void *userdata, const void *key);
    bool (SDLCALL *keymatch)(void *userdata, const void *a, const void *b);
    void (SDLCALL *destroy)(void *userdata, const void *key, const void *value);
    void *userdata;
    Uint32 hash_mask;
    Uint32 max_probe_len;
    Uint32 num_occupied_slots;
};
void squash_repro_hashtable_test(void);
void squash_repro_hashtable_test(void)
{
    SDL_Log("squash_repro_hashtable_test: calling real SDL_CreateHashTable cross-object...");
    SDL_HashTable *t = SDL_CreateHashTable(0, true, SDL_HashID, SDL_KeyMatchID, SDL_DestroyHashValue, NULL);
    SDL_Log("squash_repro_hashtable_test: SDL_CreateHashTable returned %p", (void*)t);
    if (!t) { SDL_Log("squash_repro_hashtable_test: table is NULL, aborting"); return; }
    struct squash_repro_hashtable_shadow *shadow = (struct squash_repro_hashtable_shadow*)t;
    SDL_Log("squash_repro_hashtable_test: shadow->lock=%p shadow->table=%p shadow->hash=%p shadow->keymatch=%p shadow->destroy=%p shadow->userdata=%p shadow->hash_mask=%u shadow->max_probe_len=%u shadow->num_occupied_slots=%u",
            (void*)shadow->lock, shadow->table,
            (void*)(uintptr_t)shadow->hash, (void*)(uintptr_t)shadow->keymatch, (void*)(uintptr_t)shadow->destroy,
            shadow->userdata, shadow->hash_mask, shadow->max_probe_len, shadow->num_occupied_slots);
    const void *value = NULL;
    SDL_Log("squash_repro_hashtable_test: calling SDL_FindInHashTable...");
    bool found = SDL_FindInHashTable(t, (const void *)(uintptr_t)12345, &value);
    SDL_Log("squash_repro_hashtable_test: SDL_FindInHashTable returned %d (survived the call)", (int)found);
    SDL_DestroyHashTable(t);
    SDL_Log("squash_repro_hashtable_test: done");
}

/* PNG/JPEG decode (SDL_LoadPNG/SDL_LoadJPG/SDL_SavePNG) via stb_image.h +
 * miniz.h (both real, unmodified upstream single-header libs bundled by
 * SDL3 under src/video/) — see squash_build's own scratch-tested repros
 * for the squash compiler bugs this took (constant-expression grammar
 * missing sizeof/==/?: for the "typedef char check[COND?1:-1];"
 * compile-time-assert idiom, array-typedef declarators never being parsed
 * at all, a cast inside a constant expression such as a FourCC-style
 * packed-integer case label, a brace initializer on a non-first
 * declarator in a comma-declaration list, and the comma operator not
 * being accepted in the parser's identifier-led statement fast path).
 * STB_IMAGE_STATIC keeps every stb_image.h symbol static (no export
 * clashes); SDL_stb.c itself provides the SDL_malloc/SDL_memcpy/etc
 * macro redirection stb_image.h and miniz.h both expect. */
#include "video/SDL_stb.c"

/* render/software/SDL_blendfillrect.c intentionally NOT included: its
 * per-pixel-format blend routines (RGB555/565/XRGB8888/ARGB8888/RGB/RGBA)
 * use render/software/SDL_draw.h's FILLRECT(type, op) macro, which
 * hand-rolls a Duff's-device switch(width & 3) unroll DIRECTLY (not via
 * the shared, separately-overridable DUFFS_LOOP4 macro) — and SDL_draw.h
 * has no #include guard at all, so a from-here macro override doesn't
 * stick: every consuming .c file's own "#include \"SDL_draw.h\"" re-runs
 * the plain #define and clobbers any earlier redefinition before FILLRECT
 * is actually used, a few lines later, in that SAME unmodifiable file (no
 * seam to inject a fix into, unlike DUFFS_LOOP's own file-local override
 * pattern used elsewhere in this build). squash's switch/case parser
 * requires "case" labels to be direct children of the switch block, not
 * interleaved inside a do-while body — confirmed via -dump: this is a real
 * general parser gap (case/default labels can only appear as statements
 * directly inside a switch's own top-level body, not nested inside a
 * do-while the way Duff's device relies on), flagged for a future session
 * as a genuine switch/case codegen rework (labels-anywhere semantics), same
 * class of gap already flagged for SDL_memset4's Duff's device (see
 * [[project-squash-sdl3-build]]). Since our own PRIVATE_CreateWindowFramebuffer
 * always produces SDL_PIXELFORMAT_XRGB8888 (see above), a hand-written,
 * XRGB8888-only SDL_BlendFillRect/SDL_BlendFillRects pair — reusing the
 * already-correct SDL_BlendMode math from SDL_blendfillrect.c's real
 * XRGB8888 case, just without the per-scanline unroll — covers every case
 * this build can actually reach. */
static bool squash_BlendFillRect_XRGB8888(SDL_Surface *dst, const SDL_Rect *rect,
                                           SDL_BlendMode blendMode, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
{
    int x, y;
    int pitch = dst->pitch / 4;
    Uint32 *base = (Uint32 *)dst->pixels + rect->y * pitch + rect->x;
    unsigned inva = 0xff - a;

    for (y = 0; y < rect->h; y++) {
        Uint32 *pixels = base + y * pitch;
        for (x = 0; x < rect->w; x++) {
            unsigned dr = (pixels[x] >> 16) & 0xFF;
            unsigned dg = (pixels[x] >> 8) & 0xFF;
            unsigned db = pixels[x] & 0xFF;
            unsigned sr = r, sg = g, sb = b;
            switch (blendMode) {
                case SDL_BLENDMODE_BLEND:
                    sr = ((inva * dr) / 255) + r;
                    sg = ((inva * dg) / 255) + g;
                    sb = ((inva * db) / 255) + b;
                    break;
                case SDL_BLENDMODE_ADD:
                    sr = dr + r; if (sr > 0xff) sr = 0xff;
                    sg = dg + g; if (sg > 0xff) sg = 0xff;
                    sb = db + b; if (sb > 0xff) sb = 0xff;
                    break;
                case SDL_BLENDMODE_MOD:
                    sr = (dr * r) / 255;
                    sg = (dg * g) / 255;
                    sb = (db * b) / 255;
                    break;
                case SDL_BLENDMODE_MUL:
                    sr = ((r * dr) + (dr * (255 - a))) / 255; if (sr > 0xff) sr = 0xff;
                    sg = ((g * dg) + (dg * (255 - a))) / 255; if (sg > 0xff) sg = 0xff;
                    sb = ((b * db) + (db * (255 - a))) / 255; if (sb > 0xff) sb = 0xff;
                    break;
                default:
                    break;
            }
            pixels[x] = (0xFFu << 24) | (sr << 16) | (sg << 8) | sb;
        }
    }
    return true;
}

bool SDL_BlendFillRect(SDL_Surface *dst, const SDL_Rect *rect, SDL_BlendMode blendMode, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
{
    SDL_Rect clipped;
    if (!dst || !rect) {
        return SDL_InvalidParamError("dst/rect");
    }
    if (!SDL_GetRectIntersection(rect, &dst->clip_rect, &clipped)) {
        return true;
    }
    return squash_BlendFillRect_XRGB8888(dst, &clipped, blendMode, r, g, b, a);
}

bool SDL_BlendFillRects(SDL_Surface *dst, const SDL_Rect *rects, int count, SDL_BlendMode blendMode, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
{
    int i;
    if (!dst || !rects) {
        return SDL_InvalidParamError("dst/rects");
    }
    for (i = 0; i < count; i++) {
        if (!SDL_BlendFillRect(dst, &rects[i], blendMode, r, g, b, a)) {
            return false;
        }
    }
    return true;
}

#include "render/software/SDL_blendline.c"
#include "render/software/SDL_blendpoint.c"
#include "render/software/SDL_drawline.c"
#include "render/software/SDL_drawpoint.c"
#include "render/software/SDL_triangle.c"
#include "render/software/SDL_render_sw.c"
#include "render/SDL_render.c"

/* SDL_internal.h (included by every SDL .c file above) pulls in
 * <SDL3/SDL_main.h>, which "#define main SDL_main" so a real app's main()
 * gets renamed and wrapped by SDL's own platform-specific launcher. We
 * don't build that launcher here (it's not part of this subset), so
 * without this #undef our own main() below would silently become
 * "SDL_main" in the compiled output — squash's entry-point RVA is found
 * by name-searching for a function literally called "main", so it would
 * fail to find one and default to offset 0 (the very start of .text),
 * making the OS execute whatever unrelated function happens to be first
 * instead of main() at all. */
#undef main

/* Stubs for subsystems (video/audio/render/tray/notifications) that are
 * intentionally excluded from this reduced unity build (see the file
 * header comment) but whose cleanup functions SDL_Quit() unconditionally
 * calls regardless of which subsystems were actually initialized. These
 * are genuine SDL3 functions with no real body reachable in this build —
 * not a squash bug — so no-op stubs matching their real signatures let
 * SDL_Quit() complete instead of calling into a bogus fallback import. */
void SDL_HelperWindowDestroy(void) {}
void SDL_CleanupTrays(void) {}
void SDL_CleanupNotifications(void) {}
/* SDL_QuitSubSystem() is written so every subsystem's quit function is
 * safely callable even if that subsystem was never initialized — when
 * called from SDL_Quit() itself (SDL_bInMainQuit==true),
 * SDL_ShouldQuitSubsystem() unconditionally returns true for every
 * subsystem regardless of its real refcount, specifically so a program
 * that never touched video/audio/render still gets a clean full
 * shutdown. Since this build excludes the real render/gpu subsystems
 * entirely (see file header comment), their quit functions are genuinely
 * undefined here — same "no real body reachable in this build" situation
 * as SDL_HelperWindowDestroy above, not a squash bug.
 * SDL_QuitAudio() is no longer stubbed here: audio/SDL_audio.c (now
 * included, see the PRIVATEAUDIO_* backend above) provides the real
 * definition.
 * SDL_AssertionsQuit() and SDL_QuitCPUInfo() are no longer stubbed here:
 * SDL_assert.c and SDL_cpuinfo.c (both included above) now provide the
 * real definitions. SDL_VideoQuit()/SDL_QuitRender()/SDL_QuitPixelFormatDetails()
 * are likewise no longer stubbed: video/SDL_video.c, render/SDL_render.c, and
 * video/SDL_pixels.c (all now included, see the PRIVATE_* video backend below)
 * provide the real definitions. */
/* SDL_TriggerBreakpoint is normally a macro (GCC inline-asm/MSVC intrinsic/
 * raise(SIGTRAP)), never a real function, on every platform SDL3 itself
 * supports — our target platform hits SDL_assert.h's final "intentionally
 * left undefined" case, so any reference to it needs a real body. It's
 * reachable transitively (assert-failure paths) but never actually
 * exercised by this demo, so a no-op is correct. */
void SDL_TriggerBreakpoint(void) {}
/* SDL_HasMainCallbacks() is defined in main/SDL_main_callbacks.c, which
 * isn't part of this build (its whole purpose is integrating with SDL's
 * own platform-specific main()/WinMain() launcher via SDL_main.h, which
 * this build deliberately bypasses — see the "#undef main" note above and
 * this build's own hand-rolled callback-loop test in main() further down).
 * video/SDL_video.c's SDL_OnWindowLiveResizeUpdate() checks it during
 * interactive window-resize dragging; returning false makes it take the
 * plain "send an expose event" branch instead, which is exactly correct
 * for a program that isn't using SDL's own callback-registration API. */
bool SDL_HasMainCallbacks(void) { return false; }
/* Never actually called (guarded by SDL_HasMainCallbacks() returning false
 * above), but still needs a real body: squash's codegen requires a
 * same-translation-unit function reference to resolve to an actual label at
 * link time, since it has no way to tell "declared but never defined,
 * genuinely external" (tolerated as a soft warning) apart from "declared,
 * no body in this TU, but not obviously an external DLL import either"
 * (a hard asm_resolve error) for a plain extern C function like this one. */
SDL_AppResult SDL_IterateMainCallbacks(bool pump_events) { (void)pump_events; return SDL_APP_CONTINUE; }

/* Raw WriteFile debug marker — bypasses C stdio buffering entirely, so it
 * survives a crash (unlike printf, which is fully-buffered once redirected
 * and loses everything on a non-graceful exit). See
 * [[feedback-squash-debug-prints]]. */
static void dbgmark(const char *s)
{
    HANDLE h = GetStdHandle((DWORD)-11);
    DWORD written;
    WriteFile(h, s, (DWORD)SDL_strlen(s), &written, NULL);
    WriteFile(h, "\n", 1, &written, NULL);
}

/* Debug-only: print "<label>=0x<16 hex digits>" via the same raw-WriteFile
 * technique as dbgmark() (see [[feedback-squash-debug-prints]]) — used to
 * compare a pointer's actual runtime value against an expected address
 * while chasing the still-open SDL_VideoInit() bootstrap[] crash. */
static void dbgmark_ptr(const char *label, unsigned long long v)
{
    char buf[64];
    int p = 0;
    const char *lbl = label;
    while (*lbl) buf[p++] = *lbl++;
    buf[p++] = '=';
    buf[p++] = '0';
    buf[p++] = 'x';
    for (int shift = 60; shift >= 0; shift -= 4) {
        int nib = (int)((v >> shift) & 0xf);
        buf[p++] = (nib < 10) ? ('0' + nib) : ('a' + (nib - 10));
    }
    buf[p] = 0;
    dbgmark(buf);
}
